server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-master.gulimall:3306/gulimall-ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  sleuth:
    redis:
      enabled: false
    sampler:
      probability: 1
  zipkin:
    base-url: http://zipkin-service.gulimall:9411
    discovery-client-enabled: false
    sender:
      type: web
  cloud:
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: http://sentinel-service.gulimall:8858
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
  redis:
    host: http://redis.gulimall
    port: 6379
  session:
    store-type: REDIS
  #暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

