spring:
  sleuth:
    redis:
      enabled: false
    sampler:
      probability: 1
  zipkin:
    base-url: zipkin-service.gulimall:9411
    discovery-client-enabled: false
    sender:
      type: web
  cloud:
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: sentinel-service.gulimall:8858
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
  redis:
    host: redis.gulimall
    port: 6379
  session:
    store-type: REDIS
  elasticsearch:
    rest:
      uris: elasticsearch.gulimall:9200
server:
  port: 8080
#开启debug日志
logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: debug
          sleuth: debug
  #暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true