server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-master.gulimall:3306/gulimall-oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  sleuth:
    redis:
      enabled: false
    sampler:
      probability: 1
  zipkin:
    base-url: http://zipkin-service.gulimall:9411
    discovery-client-enabled: false
    sender:
      type: web
  cloud:
    sentinel:
      transport:
          #配置sentinel dashboard地址
        dashboard: http://sentinel-service.gulimall:8858
          #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
  rabbitmq:
    host: http://rabbitmq.gulimall
    port: 5672
    username: guest
    password: guest
      # 虚拟主机配置
    virtual-host: /
      # 开启发送端消息抵达Queue确认
    publisher-returns: true
      # 只要消息抵达Queue，就会异步发送优先回调returnfirm
    template:
      mandatory: true
      # 手动ack消息，不使用默认的消费端确认
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    port: 6379
    host: http://redis.gulimall
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss


alipay:
  app_id: 2021000121657801
  notify_url: http://bwdrnq.natappfree.cc/payed/notify
  return_url: http://member.gulimall.com/memberOrder.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCt1ovGnp73NUsnUAH4AXnQnn7a/93yVmAAlcXBjutz4+q+1+dGG9q3nNeeI8k/uxuaI6GKM6yoUamjhoF3YxWGX7eulceAiVSGl3/5EeXofxn6YWzLD6NhwvXeDho+sHGHN+EQx7+IBZbZJMOKKpwm1ALCo5qqMXfd6Hx5LrBc3ih3paZZmNS4h6Cf8zUwsRKeAn17x7/5tI7+FZ13EWOh4e6HeDhac833hdA7MGIHVsLFY0zkM0EkXlC7hudlPNx+HHpWqCxCHCqNaupuTNST3dsW7s4qu6/0WYtmLdRWZ31/ZcZhJCwOYjFP+K+ZErUNk3tD3Vekdb5ukzT/sAxlAgMBAAECggEAZ15eOzrzF9iO2c+PfCOUheLZV+wx0/pcl7x3nUMY6w6p9dV4Zo4Fno0bAaQR9V2TajKpyf40OtpkXyKKNa2rjP25wYy61snSgz3vEPH9niSGFAZ+pLil1GoTvXjxTjmpKFin8kx0rbN1IaXkyHHR7JzBD3Atdep4dnHaIk0K/gz2/wAkzCTl1AIgaq8oPp/uEAvo5C/fDLowzmveXu5TftFGF3P1w9H71v56DSqOBQF526w5Yngs1HC2HHGA4PJuElvtdEe3G69FDIAsUIWhIOzAQep/oM8BN5MKJNSeKg5fwjRP5OTDBWGTEgQdZCyYaJNV0rsgrBMEcANDMLBxAQKBgQDybaBIcKnQjFgF6H6NeJzYhjnBhmPt9oylep+UjsfxdLYnPzN7U/spg0+XxXjW0jj7T7d8xy3zPsBbSk5ZzzRvsGtwi1nl5gJ5YSk0gZKIgFkh9I8a1+vLTWhaH9oLY0V3xEq5Ar2GGqMHuLUB8htBEwvCM6JQq3YkmkQiHOnKoQKBgQC3keqKK8UvIQFrn6ODbraqHDz50Caj5/OSezgLBHNrjBcbHPN/ButrwXaGlSPLsXXrHAckvu1Rfifk7ta+J8s7s09RFM6TEK8YnMCEKlVpDkOQAckthwhf5hipbOjVIz3qjpsSP4+gkIJXnfhi9YHtUP69gPN3fpCGuC6Fs60PRQKBgQDaVBx74OsupJZJi98dbbhj0E6HmY65qsdz6IF7ezNao2/A3Mxyj2mtM1MlLnTrkxw6SMrJF2CspqD6FmuFunRQ+iNokjd+Mq2bvwMrBF6BjIW5bNTMqhTzXV1TfUgT5W2UtTVOdcdV1PtqYtCxVedxrcNzPKk72Y9m23/s8PkkwQKBgEXA7ZV5UmE5Mnf53kFIJaL4PfdTMAuiTPzBU6dkFpOsVO9ZjfEb6QM2LVqwezygf0VKjjBZWIZZ4MDuPK1fI6vY0+/kbyaU9WPt1H2kNHZKFEQ5WX+ySu1d2ssudj7fOFzTuXsyqdoCb3TpswOvdKJ/33yU7m7eqf53KD5n6v/dAoGACTBevJ8cNOcvuXnyi8tGNzq91Hhj1an3X5rdyGb8ZYD4YgJ37OUKfQWVQCIuEq0/QLd2Q9FDeA6oZmHX0iOf4O01EX41mLH0SThNY7w8SaBDSfvvsYDIbZlIYmKkoPeXx1rjUX2fHdbyKIB5iuueYuNXoBRt0m+gazn8whKoUbU=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnOuZdLXvK6x4/31+oc5GS9SXAUIkmc1LvOEvQcDVqjOjJ6nEAPtZs6dG0LHbUSnBpRkP8+dXVUdJR8T095gYcyPn+PQnmpeRR4kfJ9E7SsPiN4iYlNoGJ5ZE4h/lMoXUvaKJ73yfPrBCh9qEiY1AXAfyl6rYAAaFNbzaD9KiG9c5Xq14OBq1+ESZiAd/SibykyEF825kM5yQoNYYvew68pTDAJKUxzdDlGVjzgkqdwMCQp/uFTMe8wBKTuveCGGhDpWLbkEBK0A8eIBed2COPkusC0Rk36XIsLpKBY8njvBkeFEC7C9dPo12pAe9oLakO5U8X5nf7gcw7m/gEtheawIDAQAB
#微信相关配置
wx:
  appId: wxd898fcb01713c658
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  notifyUrl: http://bwdrnq.natappfree.cc/pay/notify
  returnUrl: http://member.gulimall.com/memberOrder.html

  #暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto