server:
  port: 8080
spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://zipkin-service.gulimall:9411
    discovery-client-enabled: false
    sender:
      type: web
  cloud:
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: http://sentinel-service.gulimall:8858
        port: 8719
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: gulimall-third-party
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/third-party/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: gulimall-order
          uri: lb://gulimall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: gulimall-member
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: gulimall-product
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: gulimall-coupon
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: gulimall-ware
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}
        - id: renren-fast
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/renren-fast/$\{segment}

        - id: gulimall_host_route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com

        - id: gulimall_search_host_route
          uri: lb://gulimall-elasticsearch
          predicates:
            - Host=search.gulimall.com

        - id: gulimall_auth_host_route
          uri: lb://gulimall-auth
          predicates:
            - Host=auth.gulimall.com

        - id: gulimall_cart_host_route
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com

        - id: gulimall_order_host_route
          uri: lb://gulimall-order
          predicates:
            - Host=order.gulimall.com

        - id: gulimall_member_host_route
          uri: lb://gulimall-member
          predicates:
            - Host=member.gulimall.com

        - id: gulimall_seckill_host_route
          uri: lb://gulimall-seckill
          predicates:
            - Host=seckill.gulimall.com
#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'