server:
  port: 8160
  servlet:
    session:
      timeout: 30m
spring:
  sleuth:
    redis:
      enabled: false
    sampler:
      probability: 1
  zipkin:
    base-url: http://zipkin-service.gulimall:9411
    discovery-client-enabled: false
    sender:
      type: web
  cloud:
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: http://sentinel-service.gulimall:8858
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
#  thymeleaf:
#    cache: false
  redis:
    host: redis.gulimall
    port: 6379
  session:
    store-type: REDIS
github:
  clientId: ba19dcbb4644092b06aa
  clientSecret: 1f3b107d0e69fe2f625dbb7ea5149def1c9680c9
  authorizeUrl: https://github.com/login/oauth/authorize
  redirectUrl : http://auth.gulimall.com/github/oauth2/callback
  accessTokenUrl: https://github.com/login/oauth/access_token
  userInfoUrl: https://api.github.com/user

# 微信开放平台 appid
wx:
  open:
    app_id: wxed9954c01bb89b47
    # 微信开放平台 appsecret
    app_secret: a7482517235173ddb4083788de60b90e
    # 微信开放平台 重定向url
    redirect_url: http://localhost:8160/api/ucenter/wx/callback
  #暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
