server:
  port: 8080
spring:
  sleuth:
    redis:
      enabled: false
    sampler:
      probability: 1
  zipkin:
    base-url: http://zipkin-service.gulimall:9411
    discovery-client-enabled: false
    sender:
      type: web
  cloud:
    alicloud:
      access-key: 你的阿里云密钥
      secret-key: 你的阿里云密钥
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
#        bucket: gulimall-santiago
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: http://sentinel-service.gulimall:8858
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
#  aliyun:
#    sms:
#      host: https://gyytz.market.alicloudapi.com
#      path: /sms/smsSend
#      method: post
#      appcode: 2022fd3db7464a0d904a81195bc7e3b8
  redis:
    host: http://redis.gulimall
    port: 6379
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  #暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true